activeEnv: test_env
browser:
  browserName: chrome
  browserAttachScreenshot: false
  headlessMode: true
  browserTimeout: 60
environments:
  test_env:
    envName: test_env
    appUrl: http://146.59.32.4/index.php
    title: TesterSii
    currencySymbolToReplace: $
  int_env:
    envName: int_env
    title: Selenium
    appUrl: https://www.selenium.dev/
    currencySymbolToReplace: $



